### ISSUE TITLE
Inconsistency in company name length assertion 

### ISSUE THREAD

**Issue by Ciki** [AsisTeam/ares#1]
On lines https://github.com/AsisTeam/ares/blob/54e12b96c0d78200c7309ea5170156e88c7b0730/src/Entity/Subject.php#L87-L89 there's inconsistency in minimal number of required characters in condition and exception message.

**Comment by holantomas** [comment]
@Ciki Thanks for report ... Fixed https://github.com/AsisTeam/ares/commit/8bddaa75a99c717f50bde69bd42bf519694b1b7c
